### ISSUE TITLE
About DFT TEST

### ISSUE THREAD

**Issue by HotitanXiao** [dj-on-github/sp800_22_tests#1]
Hi dj, Thank you for converting sp800-22 to python code。
I also implement DFT test using python ,and get the same p_value as yours. But I am confused is why the test results of bits "1001010011" inside the sp800-22ra1 document is 0.029523,  our implement get 0.818545808382.  

Thanks.

**Comment by dj-on-github** [comment]
My code gets 0.818545808382 too.

Running it:

]# python test.py
  N0 = 4.750000
  N1 = 5.000000
success  True
P = 0.818545808382


The code:

import math
import numpy

def dft_test(bits):
    n = len(bits)
    if (n % 2) == 1:        # Make it an even number
        bits = bits[:-1]

    ts = list()             # Convert to +1,-1
    for bit in bits:
        ts.append((bit*2)-1)

    ts_np = numpy.array(ts)
    fs = numpy.fft.fft(ts_np)  # Compute DFT

    mags = abs(fs)[:n/2] # Compute magnitudes of first half of sequence

    T = math.sqrt(math.log(1.0/0.05)*n) # Compute upper threshold
    N0 = 0.95*n/2.0
    print "  N0 = %f" % N0

    N1 = 0.0   # Count the peaks above the upper theshold
    for mag in mags:
        if mag < T:
            N1 += 1.0
    print "  N1 = %f" % N1
    d = (N1 - N0)/math.sqrt((n*0.95*0.5)/4) # Compute the P value
    p = math.erfc(abs(d)/math.sqrt(2))

    success = (p >= 0.01)
    return (success,p,None)

bits = [1,0,0,1,0,1,0,0,1,1]
(s,p,_) = dft_test(bits)

print "success ",s
print "P =",p



I see in SP800-22rev1a, section 2.6.4, they state that N1 = 4.
My code and I suspect your code counts N1 = 5 (the number of peaks less
than T).

M =  [ 0.          2.          4.47213595  2.          4.47213595]
T =  5.47332830511

So all the peaks are less than 5.47
They do not give a value for T.

Things I tried:

I tested for using log_e vs log10 and that doesn't account for the N=4 in
the spec.

I tried reversing the bits, which had no effect, as you might expect.

I observe that there is no value for T for which 4 of the magnitudes are
less than T because the highest two peaks are the same, so with large T,
the answer is 5. With T just less than 4.47, the answer is 3.

So either the magnitudes are different or the spec is simply wrong. I'm
using the
default numpy FFT, which I'm confident works. So I think the spec is wrong.
There
are several other errors in the document.


In the 100 bit example, the result is different too. I get N1 = 48. The
spec gets N1 = 46.
So in both cases my implemention gets N1 > specN1.

I found an error on line 48..
   d = (N1 - N0)/math.sqrt((n*0.95*0.5)/4) # Compute the P value
Should be
   d = (N1 - N0)/math.sqrt((n*0.95*0.05)/4) # Compute the P value

But this doesn't account for the different with the NIST spec.

# python test.py
bits   [1, 0, 0, 1, 0, 1, 0, 0, 1, 1]
M =  [ 0.          2.          4.47213595  2.          4.47213595]
T =  5.47332830511
  N0 = 4.750000
  N1 = 5.000000
d  0.72547625011
success  True
P = 0.468159909854


I will take a look at NIST's implementation and see how it behaves.

DJ

**Comment by dj-on-github** [comment]
I have recreated the NIST number:

mags  [ 10.           2.           4.47213595   2.           4.47213595]
T  5.47332830552
  N0 = 4.750000
  N1 = 4.000000
success  True
p  0.0295232159499

This is achieved by erroneously converting the input bits from 0,1 to 0,2 instead of -1,+1.
The right formula is value = (2*bit)-1.

My code does it like this:
    ts = list()             # Convert to +1,-1
    for bit in bits:
        ts.append((bit*2)-1)

If I change it to:
    ts = list()             # Convert to +1,-1
    for bit in bits:
        ts.append(bit*2)

So its mapping [0,1] --> [0,2] instead of [-1.+1] we get a result that matches the NIST example.
So the spec is definitely broken.

Look here : https://github.com/kravietz/nist-sts/blob/master/discreteFourierTransform.c
This is in the NIST version of the test.

Lines 33-34 seem to do this correctly.
    for ( i=0; i<n; i++ )
        X[i] = 2*(int)epsilon[i] - 1;

I assume whatever implementation was used for the 10 bit example had the mapping bug in it.

**Comment by dj-on-github** [comment]
I've emailed the named contacts for sts-2.1.2 at NIST with details.

**Comment by HotitanXiao** [comment]
Thank you very much.

**Comment by dj-on-github** [comment]
Closing this. It's up to NIST to fix their spec.

**Comment by robplee** [comment]
Hi David, did you ever get a response from NIST about the bugs in the DFT Test Description and Example numbers?  I notice that while the (0,1)->(0,2) bug explains the former, it doesn't explain the latter and was wondering if NIST made any response to your email.

**Comment by dj-on-github** [comment]
No. NIST has not responded to that, nor the other errors I found. I've written about all the flaws I found in my book (Random Number Generators, Principles and Practices). I'm going to make representations through the CMUF entropy working group.
