### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by phireiser** [dj-on-github/sp800_22_tests#12]
Hey,
I am running in to a problem when trying to execute the randomness tests.
My Setup: 16GB RAM; Fedora 29; random-bits-file is about 100MB in size; swap-partion: 8GB; Python 2.7.15 installed; Python 3.7.2 installed
**Reproducing steps in Fedora** 

- Start the test with `pyhton3 sp800_22_tests.py random-bit-file`
Test runs with about 40% RAM allocated. When coming to the DFT-test the allocation increases to the maximum.  See [sp800-22_memorry_error.txt](https://github.com/dj-on-github/sp800_22_tests/files/3053787/sp800-22_memorry_error.txt) and [sp800-22_memorry_error2.txt](https://github.com/dj-on-github/sp800_22_tests/files/3053790/sp800-22_memorry_error2.txt) for details.

- Note that calling the tests with the "old" python 2.7 results in a simple `Killed` message during the runs_test: [sp800-22_killed.txt](https://github.com/dj-on-github/sp800_22_tests/files/3053854/sp800-22_killed.txt)

**Comment by dj-on-github** [comment]
My initial thought was "That's a lot of data for the SP800-22 tests". In SP800-22rev1 in the DFT test we have "Section 2.6.7 Input Size Recommendation. Is it recommended that each sequence to be test consist of a minimum of 1000 bits (i.e. n >= 1000)."

I recreated it with 100 MiBytes of uniform random data:

# quickrdrand -b -k 102400 > random-bit-file
# python2 sp800_22_tests.py -t dft_test random-bit-file
Tests of Distinguishability from Random
TEST: dft_test
Segmentation fault (core dumped)

You are performing a DFT on a 100MiBytes of data. That is a string of 838,860,800 bits. The first step of the test is to compute a DFT over those bits as a single bit string. Since numpy is being used, those bits are turned into floats. So that's an array of 6.7 Gbytes of floating point data - for the first copy of the array. The test goes on to make copies - first the +- array, then the modulus. So 3.5 times as much. This is why it's running out of data. 

On solution is to re-work the code to throw out old arrays to make room for the new. Or work in-place. My original version did this, with a native python FFT algorithm, but it was slow compared to numpy.

The easier solution is to use smaller files.

In general, this is one of many flaws in the specification. Distinguishability testing generally demands large data sets to get sufficient confidence, but the SP800-22 algorithms are simply not designed for large data sets.

**Comment by dj-on-github** [comment]
Closing since there isn't much to be done. Wait a few years and computer memory might increase to make this go away.
